server:
  port: 80

#spring 配置
spring:
  application:
    name: springcloud-consumer-dept

eureka:
  client:
    service-url:
      defaultZone: http://eurekaA.com:7001/eureka/,http://eurekaB.com:7001/eureka/,http://eurekaC.com:7001/eureka/
    register-with-eureka: false
