server:
  port: 7001

#eureka
eureka:
  instance:
    hostname: eurekaA.com
  client:
    # 默认情况下，Eureka Server 也是一个微服务，所以当它还是一个注册中心的时候，它会有两层身份：1.注册中心，2.普通微服务，
    # register-with-eureka 设置为 false ，表示当前项目不要注册到注册中心。
    register-with-eureka: false
    # 表示是否从 Eureka Server 上获取注册表信息
    fetch-registry: true
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eurekaB.com:7002/eureka,http://eurekaC.com:7003/eureka
#Spring
spring:
  application:
    name: springcloud-eureka7001