server:
  port: 8001

 #mybatis-plus
mybatis-plus:
  type-aliases-package: com.zhou.springcloud.pojo
  #config-location: classpath*:mybatis/mybatisplus-config.xml
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhoudb?useUnicode=true&charactorEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

#eureka
eureka:
  client:
    service-url:
      defaultZone:  http://eurekaA.com:7001/eureka/,http://eurekaB.com:7002/eureka,http://eurekaC.com:7003/eureka
  instance:
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
    instance-id:  springcloud-provider-dept:8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true

#actuator 监控信息
info:
  app.name: springcloud-provider-dept
  company.name: www.zhou.com
  #build.artifactId: @project.artifactId@
  #build.version:  @project.version@
