server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone:  http://eurekaA.com:7001/eureka/,http://eurekaB.com:7002/eureka,http://eurekaC.com:7003/eureka
  instance:
    instance-id: springcloud-zuul:9527
    prefer-ip-address: true

info:
  app.name: springcloud-provider-dept
  company.name: www.zhou.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept #实际服务
    mydept.path: /mydept/**  #自定义服务
  ignored-services: springcloud-provider-dept
  prefix: /zhou  #设置公共的服务
